version: '3'

services:
  app:
    build:
      context: .
      dockerfile: docker/production/django/Dockerfile
    image: loan_management_production_app
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    volumes:
      - .:/opt/services/loan_management/src
      - production_static_volume:/opt/services/loan_management/src/static
      - production_media_volume:/opt/services/loan_management/src/media
    networks:
      - production_nginx_network
      - production_postgres_network
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: docker/production/nginx/Dockerfile
    image: loan_management_production_nginx
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - production_static_volume:/opt/services/loan_management/src/static
      - production_media_volume:/opt/services/loan_management/src/media
    depends_on:
      - app
    networks:
      - production_nginx_network

  postgres:
    build:
      context: .
      dockerfile: docker/production/postgres/Dockerfile
    image: loan_management_production_postgres
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - production_postgres_network
    volumes:
      - production_postgres_volume:/var/lib/postgres/data

networks:
  production_nginx_network:
    driver: bridge
  production_postgres_network:
    driver: bridge

volumes:
  production_postgres_volume:
  production_static_volume:
  production_media_volume:
