# Generated by Django 2.2.2 on 2019-06-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
